name: Pull Request Test

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  IS_PR: ${{github.event_name == 'pull_request' || ''}}
  IS_MAIN: ${{github.event_name == 'push' || ''}}

jobs:
  test:
    name: Test compile golang and run go tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-
          path: |
            ~/.cache/golangci-lint
            ~/.cache/go-build
            ~/go/pkg/mod

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: ./go.mod
          cache: false

      - name: Run linters
        run: go mod tidy && make lint

      - name: Run tests
        run: make test/unit

      - name: make build
        run: make bin

      - uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        if: ${{ env.IS_MAIN }}
        with:
          key: ${{ runner.os }}-go-cache-${{ hashFiles('**/go.sum') }}
          path: |
            ~/.cache/golangci-lint
            ~/.cache/go-build
            ~/go/pkg/mod
